@echo off
echo Iniciando sistema na porta 3002...
echo Parando processos antigos na porta 3000...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3000') do (
    taskkill /PID %%a /F >nul 2>&1
)
echo Iniciando servidor e frontend na porta 3002...
start cmd /k "npm run dev:full" 